### ISSUE TITLE
beginTransmission(): Unfinished Repeated Start transaction! Expected requestFrom, not beginTransmission! Clearing...

### ISSUE THREAD

**Issue by jake-is-ESD-protected** [sparkfun/SparkFun_Qwiic_OLED_Arduino_Library#19]
I am not able to display correct information on the SFE Micro OLED (SSD1306) using an ESP32 WROOM with PlatformIO and the Arduino FW. 
Only garbled pixels are shown and the ESP32 logs the following warning:

![Capture](https://github.com/sparkfun/SparkFun_Qwiic_OLED_Arduino_Library/assets/78532991/d9396d68-5827-434a-9723-f17773573aee)
```
[  6624][E][Wire.cpp:416] beginTransmission(): Unfinished Repeated Start transaction! Expected requestFrom, not beginTransmission! Clearing...
```

The issue might not come from your side of the library, it seems to be a conflict in `Wire`. However, I would like to confirm that this happens on your test devices too. I can **confirm** that it is not a hardware issue, as I observed the same behavior on different Micro OLEDs and on different ESP32s. I even have an ESP32 with firmware that was flashed about 3 years ago that runs the display just fine. I tried reverting to the versions of your library and `Wire` at that time but without success. Any [example](https://github.com/sparkfun/SparkFun_Qwiic_OLED_Arduino_Library/tree/main/examples) fails with the same issue.

Can you confirm this?

**Comment by PaulZC** [comment]
Hi Jakob (@jake-is-ESD-protected ),

Nope. Sorry. The library and examples work just fine for us on ESP32. But, we don't use PlatformIO and I have no idea what version of the Arduino ESP32 core it is using... Please give the examples another try using regular Arduino IDE and the latest ESP32 core / board package.

If you think we can help, please re-open.

Best wishes,
Paul
