### ISSUE TITLE
Can not get this to work with Sparkfun 52840 board mini

### ISSUE THREAD

**Issue by sskindell** [sparkfun/SparkFun_Qwiic_OLED_Arduino_Library#22]
No output .. imported files etc.
Nothing.

**Comment by PaulZC** [comment]
Hi @sskindell ,

The library is working OK for me using v1.6.0 of the Adafruit nRF52 board package:


https://github.com/sparkfun/SparkFun_Qwiic_OLED_Arduino_Library/assets/5690545/c2afa3bb-ebb7-4d50-9677-de13d01eff96


Please check you have followed all of the instructions here: https://learn.sparkfun.com/tutorials/nrf52840-development-with-arduino-and-circuitpython#arduino-installation

Best wishes,
Paul
