### ISSUE TITLE
GNU Licensing?

### ISSUE THREAD

**Issue by zyphlar** [sparkfun/SparkFun_Qwiic_OLED_Arduino_Library#23]
Hi there! In other libraries and in most of this one, SparkFun uses the MIT license, but the `res/_bmp*` and `res/_fnt*` files in this repo say they're GNU GPL. Is that the case or do those files also need to be updated?

Thanks!

**Comment by edspark** [comment]
Yes unfortunately I don't see any reason why that wouldn't be the case. As mentioned at the top of the file:
```
"This file was imported from the MicroView library, written by GeekAmmo
(https://github.com/geekammo/MicroView-Arduino-Library), and released under 
the terms of the GNU General Public License as published by the Free Software 
Foundation, either version 3 of the License, or (at your option) any later 
version."
```

...and navigating to the [Microview Arduino Library](https://github.com/geekammo/MicroView-ARduino-library), the licensing is consistent with what's mentioned in the comment above. It's been a long time but I don't see any reason as to why this would change. 

Hope that helps!
