### ISSUE TITLE
Minor corrections

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_Qwiic_OLED_Arduino_Library#4]
Hi folks,

Just a couple of odds and ends.

1) There's a URL typo in README.md on line 22 that points to the incorrect product (should be https://www.sparkfun.com/products/14532)

2) I've noticed the `myOLED.text()` keyword isn't properly highlighting itself in the Arduino IDE. I checked keywords.txt and it looks fine. Not a big issue, but strange!

Cheers,
Adam

**Comment by nseidle** [comment]
Good eyes. Typo fixed. 

.text() is highlighting for me. I fixed the keywords file just the other day. Maybe you have old version?

![image](https://user-images.githubusercontent.com/117102/160201224-2a7c5845-c953-4205-a644-e1763c311196.png)

**Comment by adamgarbo** [comment]
Whoops, that did it! Installed the library for the first time yesterday and didn't spot the update.
