### ISSUE TITLE
Update name of library in library.properties?

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_Qwiic_OLED_Arduino_Library#8]
Hi folks,

I noticed the name of this library in `library.properties` is currently `SparkFun Qwiic OLED Graphics Library`. Should it instead be `SparkFun_Qwiic_OLED_Arduino_Library`? By the looks of it, you've done away with the older library. My Arduino IDE was getting a bit confused as with multiple libraries.

Cheers,
Adam

**Comment by kirk-sfe** [comment]
Good catch - yes, this was an oversight when I copied over a file from the old library. Fixed, checked in  and will get in next release. 

FYI - The older library will continue to exist, but we don't plan to do any more updates to it. This library is where our focus is going forward.

Thanks!
-Kirk
